name: build version

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string
      dotnet-version:
        description: 'Dotnet version to build'
        required: true
        type: string

    outputs:
      version:
        description: 'Version built'
        value: ${{ inputs.version }}

jobs:
  build-version-publish:
    runs-on: ubuntu-latest

    steps:
      - name:  Setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Display version .NET
        run: dotnet --version

      - name: Checkout repository
        uses: actions/checkout@v1 

      - name: Build publish version
        run: dotnet publish -o version-${{github.run_number}}-${{inputs.dotnet-version}}

      - name: Copy asdf file to publish version 
        run: cp .tool-versions version-${{github.run_number}}-${{inputs.dotnet-version}}/

      - name: Upload publish folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.version }}
          path: version-${{github.run_number}}-${{inputs.dotnet-version}}/
          include-hidden-files: true
  