name: build version
description: 'Build a version of the project with a specified .NET version and upload as artifact'

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string
      dotnet-version:
        description: 'Dotnet version to build'
        required: true
        type: string
      path_asdf_tool_version:
        description: 'Whether to include .tool-versions file in the artifact, pass path to the file'
        required: false
        type: string
        default: ''

    outputs:
      version_built:
        description: 'Version built'
        value: ${{ inputs.version }}

jobs:
  build-version-publish:
    runs-on: ubuntu-latest

    steps:
      - name:  Setup .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Display version .NET
        run: dotnet --version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build publish version
        run: dotnet publish -o version-${{github.run_number}}-${{inputs.dotnet-version}}

      - name: Copy asdf file to publish version 
        if: ${{ inputs.path_asdf_tool_version != '' }}
        run: cp ${{inputs.path_asdf_tool_version}} version-${{github.run_number}}-${{inputs.dotnet-version}}/

      - name: Upload publish folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.version }}
          path: version-${{github.run_number}}-${{inputs.dotnet-version}}/
          include-hidden-files: true
  