name: Save SSH Key

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        description: 'SSH Private Key'
        required: true
      SSH_HOST:
        description: 'SSH Host'
        required: true
      SSH_PORT:
        description: 'SSH Port'
        required: true
      SSH_USERNAME:
        description: 'SSH Username'
        required: true
    
    inputs:
      ssh_key_path:
        description: 'Path to save the SSH key'
        required: false
        default: '/tmp/id_rsa'
        type: string
        
    outputs:
      ssh-key-path:
        description: 'Path to the saved SSH key'
        value: ${{ inputs.ssh_key_path }}

jobs:
  save-ssh-key:
    runs-on: ubuntu-latest
    steps:
    - name: Save ssh key
      run: |
        # Save the private SSH key to a file
        echo -e "${{ secrets.SSH_PRIVATE_KEY}}" > ${{ inputs.ssh_key_path }}
        chmod 600 ${{ inputs.ssh_key_path }}

    - name: Ensure SSH directory exists
      run: mkdir -p ~/.ssh

    - name: Test SSH Connection
      run: ssh -i ${{ inputs.ssh_key_path }}  -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"